add a namespace
error was:
Error: query: failed to query with labels: secrets is forbidden: User "gh-netex-photon-41a1-dev@ent-github-shr.iam.gserviceaccount.com" cannot list resource "secrets" in API group "" in the namespace "netex-photon": requires one of ["container.secrets.list"] permission(s).
helm.go:92: 2025-06-04 09:08:19.817417461 +0000 UTC m=+0.933705133 [debug] secrets is forbidden: User "gh-netex-photon-41a1-dev@ent-github-shr.iam.gserviceaccount.com" cannot list resource "secrets" in API group "" in the namespace "netex-photon": requires one of ["container.secrets.list"] permission(s).
query: failed to query with labels